apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two-deployment
  namespace: apps
  labels:
    app: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: app-two
        image: olisyma/goapp
        env:
        - name: APP_NAME
          value: "APP 2"
        ports:
        - containerPort: 80
