Vagrant.configure(2) do |config|
    config.vm.box = "fedora/40-cloud-base"
    config.vm.box_version = "40.20240414.0"
    config.ssh.extra_args = ["-o", "PubkeyAcceptedKeyTypes=+ssh-rsa", "-o", "HostKeyAlgorithms=+ssh-rsa"]
      
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
    end

    config.vm.define "psimonen" do |control|
        control.vm.hostname = "psimonenS"
        control.vm.network "public_network", ip: "192.168.56.110"
        # config.vm.provision :shell, :inline => SHELL
        #     [...]
        # SHELL
        #     control.vm.provision "shell", path: REDACTED
    end

    config.vm.define "valmpani" do |control|
        control.vm.hostname = "valmpaniSW"
        control.vm.network "public_network", ip: "192.168.56.111"
        # config.vm.provider "virtualbox" do |v|
        #     v.memory = 1024
        #     v.cpus = 1
        # end
        # config.vm.provision "shell", inline: <<-SHELL
        #     [..]
        # SHELL
        #     control.vm.provision "shell", path: REDACTED
    end

end
