# K3s cluster with master and agent nodes
vagrant_box = "generic/debian12"

server_ip = "192.168.56.110"
server_vmname = "psimonen"
server_hostname = "psimonenS"
server_cpu = 1
server_ram = 1024

agent_ip = "192.168.56.111"
agent_vmname = "valmpani"
agent_hostname = "valmpaniSW"
agent_cpu = 1
agent_ram = 512

token_path = "/vagrant_share/token"

Vagrant.configure(2) do |config|
    config.vm.box = vagrant_box

    config.vm.define server_vmname do |server|
        server.vm.provider "virtualbox" do |v|
            v.memory = server_ram
            v.cpus = server_cpu
        end
        server.vm.hostname = server_hostname
        server.vm.network "private_network", ip: server_ip, hostname: true
        server.vm.synced_folder "./confs", "/vagrant_share"
        server.vm.provision "shell", inline: <<-SHELL
            echo 'k3s server'
            export INSTALL_K3S_EXEC="--bind-address #{server_ip} --flannel-iface eth1"
            curl -sfL https://get.k3s.io | sh -
            sleep 5
            cp /var/lib/rancher/k3s/server/node-token "#{token_path}"
            cp /etc/rancher/k3s/k3s.yaml /vagrant_share/
            SHELL
    end

    config.vm.define agent_vmname do |agent|
        agent.vm.provider "virtualbox" do |v|
            v.memory = agent_ram
            v.cpus = agent_cpu
        end
        agent.vm.hostname = agent_hostname
        agent.vm.network "private_network", ip: agent_ip, hostname: true
        agent.vm.synced_folder "./confs", "/vagrant_share"
        agent.vm.provision "shell", inline: <<-SHELL
            echo 'k3s agent'
            export K3S_TOKEN_FILE="#{token_path}"
            export K3S_URL="https://#{server_ip}:6443"
            export INSTALL_K3S_EXEC="--flannel-iface eth1"
            curl -sfL https://get.k3s.io | sh -
            SHELL
    end
end
