Vagrant.configure(2) do |config|
    config.vm.box = "generic/debian12"
      
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
        v.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end

    config.vm.define "psimonen" do |control|
        control.vm.hostname = "psimonenS"
        control.vm.network "private_network", ip: "192.168.56.110"
        # config.vm.provision :shell, :inline => SHELL
        #     [...]
        # SHELL
        #     control.vm.provision "shell", path: REDACTED
    end

    config.vm.define "valmpani" do |control|
        control.vm.hostname = "valmpaniSW"
        control.vm.network "private_network", ip: "192.168.56.111"
        # config.vm.provision "shell", inline: <<-SHELL
        #     [..]
        # SHELL
        #     control.vm.provision "shell", path: REDACTED
    end
end
